import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Zen_Kaku_Gothic_New } from 'next/font/google';
import { Playfair_Display, Noto_Serif_JP, Archivo } from 'next/font/google';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({ 
	subsets: ['latin'] 
});

const zenKaku = Zen_Kaku_Gothic_New({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'], 
  display: 'swap',
  variable: '--font-zen-kaku', 
});

const notoSerif = Noto_Serif_JP({
  subsets: ['latin'],
  variable: '--font-noto-serif',
  weight: ['200', '300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}

    >
      <body className="min-h-full flex flex-col"
	  	  style={{
			fontFamily: `${archivo.style.fontFamily}, ${zenKaku.style.fontFamily}, sans-serif`,
			}}
			>{children}</body>
    </html>
  );
}
